on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ARMmbed/mbed-os-example-blinky
      - uses: OUXT-Polaris/build-mbed-app-action@master